### ISSUE TITLE
Hi, few shot tuning 

### ISSUE THREAD

**Issue by bitwangdan** [bingykang/Fewshot_Detection#11]
Thank you very much for your code, which is very interesting. But I have a question，
This is the result of my base training 
![image](https://user-images.githubusercontent.com/18326564/67666135-1bee4c00-f9a6-11e9-87ab-a90aaee149f2.png)
This is the result of my few shot tuning
![image](https://user-images.githubusercontent.com/18326564/67666653-337a0480-f9a7-11e9-8edf-8261b005a259.png)
The MAP of novel class is better , but the base class is worse, is there something wrong?

**Comment by liuzhuang13** [comment]
Did you fine-tune with both novel & base classes or just novel classes?

**Comment by bingykang** [comment]
If you are using my code and config file without any change, you should test the fifth checkpoint or change "max_epoch" in "metatune.data" to 1000 instead of 2000 for 5-shot detection.

**Comment by bitwangdan** [comment]
> Did you fine-tune with both novel & base classes or just novel classes?

![image](https://user-images.githubusercontent.com/18326564/67740821-22d29880-fa52-11e9-925a-ca41217e8dd5.png)
Hi, I have a question, what does this weightfile mean? is the result of base training?

**Comment by bitwangdan** [comment]
> If you are using my code and config file without any change, you should test the fifth checkpoint or change "max_epoch" in "metatune.data" to 1000 instead of 2000 for 5-shot detection.

Hi，I trained according to your steps, 
![image](https://user-images.githubusercontent.com/18326564/67740915-7513b980-fa52-11e9-899d-c256da018dde.png)
and what does this weightfile mean?

**Comment by bitwangdan** [comment]
> If you are using my code and config file without any change, you should test the fifth checkpoint or change "max_epoch" in "metatune.data" to 1000 instead of 2000 for 5-shot detection.
Hi,
This is the way I tested before:
(1)  python valid_ensemble.py cfg/metatune.data cfg/darknet_dynamic.cfg cfg/reweighting_net.cfg backup/metatunetest1_novel0_neg0/000010.weights
(2) python scripts/voc_eval.py results/metatunetest1_novel0_neg0/ene000010/comp4_det_test_

I changed the 000010.weights to 000005.weights, but the result is also like this.

**Comment by XinyiYS** [comment]
Got the same problem as @bitwangdan . The final evaluated results are not the same as @bitwangdan reproduced here, but are similar
<img width="200" alt="Screenshot 2019-11-01 at 4 26 11 PM" src="https://user-images.githubusercontent.com/17292375/68012264-8237df00-fcc4-11e9-822c-8e081cd5c7bf.png">

I have also tried with changing 000010.weights to 00000x.weights, and the evaluation results stay the same.

**Comment by m10507323** [comment]
@bitwangdan Hi, can I ask how to install pytorch 0.3.1 with python2.7?
Because the error said I can't install numpy in python2.7, and the python version need >=3.5 when I install torch and torchvision.
Do you have this problem when implement the source code?
Thanks.

**Comment by futureisatyourhand** [comment]
> Got the same problem as @bitwangdan . The final evaluated results are not the same as @bitwangdan reproduced here, but are similar
> <img alt="Screenshot 2019-11-01 at 4 26 11 PM" width="200" src="https://user-images.githubusercontent.com/17292375/68012264-8237df00-fcc4-11e9-822c-8e081cd5c7bf.png">
> 
> I have also tried with changing 000010.weights to 00000x.weights, and the evaluation results stay the same.
You should carefully analyze the eval code, and you should delete the annts.pkl file when you evaluate it, and the evaluation result is the current result.

> Got the same problem as @bitwangdan . The final evaluated results are not the same as @bitwangdan reproduced here, but are similar
> <img alt="Screenshot 2019-11-01 at 4 26 11 PM" width="200" src="https://user-images.githubusercontent.com/17292375/68012264-8237df00-fcc4-11e9-822c-8e081cd5c7bf.png">
> 
> I have also tried with changing 000010.weights to 00000x.weights, and the evaluation results stay the same.

You should carefully analyze the eval code, and you should delete the annts.pkl file when you evaluate it, and the evaluation result is the current result.

**Comment by futureisatyourhand** [comment]
> 与@bitwangdan遇到相同的问题。最终评估结果与此处复制的@bitwangdan不同，但相似
> <img alt="屏幕截图2019-11-01在4 26 11 PM" width="200" src="https://user-images.githubusercontent.com/17292375/68012264-8237df00-fcc4-11e9-822c-8e081cd5c7bf.png">
> 
> 我还尝试将000010.weights更改为00000x.weights，并且评估结果保持不变。



> Got the same problem as @bitwangdan . The final evaluated results are not the same as @bitwangdan reproduced here, but are similar
> <img alt="Screenshot 2019-11-01 at 4 26 11 PM" width="200" src="https://user-images.githubusercontent.com/17292375/68012264-8237df00-fcc4-11e9-822c-8e081cd5c7bf.png">
> 
> I have also tried with changing 000010.weights to 00000x.weights, and the evaluation results stay the same.

Excuse me, is your training  setting exactly the same as the author？
Thanks!

**Comment by XinyiYS** [comment]
> Excuse me, is your training setting exactly the same as the author？

Yes, I followed the configurations and the setting by the repo exactly. The results after base training were on par with the author's results. But I _cannot_ seem to get as good results after few-shot fine-tune as the author's results.

On a side-node about Github: why, all of a sudden, am I reading some sort-of mandarin translation of my previous comment? lol

**Comment by futureisatyourhand** [comment]
> > Excuse me, is your training setting exactly the same as the author？
> 
> Yes, I followed the configurations and the setting by the repo exactly. The results after base training were on par with the author's results. But I _cannot_ seem to get as good results after few-shot fine-tune as the author's results.
> 
> On a side-node about Github: why, all of a sudden, am I reading some sort-of mandarin translation of my previous comment? lol

When I train 1500 epochs by two 1080Ti GPUs, The best base class evaluation result is shown.
![author_1130](https://user-images.githubusercontent.com/40520052/69928313-3613d080-14f6-11ea-9dfb-a6524185b6de.png)
and I don't know why the base result is poor. 
Are you train base model with four GPUs?
Thanks your reply!

**Comment by XinyiYS** [comment]
> > > Excuse me, is your training setting exactly the same as the author？
> > 
> > 
> > Yes, I followed the configurations and the setting by the repo exactly. The results after base training were on par with the author's results. But I _cannot_ seem to get as good results after few-shot fine-tune as the author's results.
> > On a side-node about Github: why, all of a sudden, am I reading some sort-of mandarin translation of my previous comment? lol
> 
> When I train 1500 epochs by two 1080Ti GPUs, The best base class evaluation result is shown.
> ![author_1130](https://user-images.githubusercontent.com/40520052/69928313-3613d080-14f6-11ea-9dfb-a6524185b6de.png)
> and I don't know why the base result is poor.
> Are you train base model with four GPUs?
> Thanks your reply!

Is this after base training alone, or after base training AND fine tuning?

Yeah, I carried our the base training with four GPUs.

**Comment by futureisatyourhand** [comment]
> base training alone

this is  the base training alone

**Comment by futureisatyourhand** [comment]
> > > > Excuse me, is your training setting exactly the same as the author？
> > > 
> > > 
> > > Yes, I followed the configurations and the setting by the repo exactly. The results after base training were on par with the author's results. But I _cannot_ seem to get as good results after few-shot fine-tune as the author's results.
> > > On a side-node about Github: why, all of a sudden, am I reading some sort-of mandarin translation of my previous comment? lol
> > 
> > 
> > When I train 1500 epochs by two 1080Ti GPUs, The best base class evaluation result is shown.
> > ![author_1130](https://user-images.githubusercontent.com/40520052/69928313-3613d080-14f6-11ea-9dfb-a6524185b6de.png)
> > and I don't know why the base result is poor.
> > Are you train base model with four GPUs?
> > Thanks your reply!
> 
> Is this after base training alone, or after base training AND fine tuning?
> 
> Yeah, I carried our the base training with four GPUs.
this is the base training alone

**Comment by XinyiYS** [comment]
> > this is the base training alone

Not sure if using 2 GPUs instead of 4 would affect the effectiveness of training. Probably the authors are best equipped to answer your questions.

Naively, i think you might try loading the last weights file of the model and continue with base training for some more epochs and see if the evaluation results improve. In my opinion, the base training should not cause much trouble since the it relies more on YOLOv2 and darknet back-bone and is essentially training a normal supervised learning object detection model with well-tested architecture (YOLOv2).

**Comment by futureisatyourhand** [comment]
> > > this is the base training alone
> 
> Not sure if using 2 GPUs instead of 4 would affect the effectiveness of training. Probably the authors are best equipped to answer your questions.
> 
> Naively, i think you might try loading the last weights file of the model and continue with base training for some more epochs and see if the evaluation results improve. In my opinion, the base training should not cause much trouble since the it relies more on YOLOv2 and darknet back-bone and is essentially training a normal supervised learning object detection model with well-tested architecture (YOLOv2).

Thank your reply, I will continue to train the base.

**Comment by XinyiYS** [comment]
> Thank your reply, I will continue to train the base.

I shared the my trained model (only after base training), here #19 
Maybe you could the weights directly instead of trying to figure out how to get the base training to work.

**Comment by futureisatyourhand** [comment]
> > Thank your reply, I will continue to train the base.
> 
> I shared the my trained model (only after base training), here #19
> Maybe you could the weights directly instead of trying to figure out how to get the base training to work.

Thank your suggestion, I mainly use this method for other work and improve the performance. In a short, thank you very much!

**Comment by futureisatyourhand** [comment]
> > Thank your reply, I will continue to train the base.
> 
> I shared the my trained model (only after base training), here #19
> Maybe you could the weights directly instead of trying to figure out how to get the base training to work.

Hello, what is the configuration of your server environment? As configured by the author, I train 150 epochs, but the detection result is much worse than yours for base classes.
Thank your reply!

**Comment by futureisatyourhand** [comment]
> > Thank your reply, I will continue to train the base.
> 
> I shared the my trained model (only after base training), here #19
> Maybe you could the weights directly instead of trying to figure out how to get the base training to work.

Hello, what is the configuration of your server environment? As configured by the author, I train 150 epochs, but the detection result is much worse than yours for base classes.
Thank your reply!

**Comment by futureisatyourhand** [comment]
> Thank you very much for your code, which is very interesting. But I have a question，
> This is the result of my base training
> ![image](https://user-images.githubusercontent.com/18326564/67666135-1bee4c00-f9a6-11e9-87ab-a90aaee149f2.png)
> This is the result of my few shot tuning
> ![image](https://user-images.githubusercontent.com/18326564/67666653-337a0480-f9a7-11e9-8edf-8261b005a259.png)
> The MAP of novel class is better , but the base class is worse, is there something wrong?

Hello, how many epochs do you train this result on the base class?
Thanks~

**Comment by XinyiYS** [comment]
> Hello, what is the configuration of your server environment? As configured by the author, I train 150 epochs, but the detection result is much worse than yours for base classes.
> Thank your reply!

I followed the author's config and environment pretty much exactly. So I am not very sure why training on different servers results quite different results. Perhaps run through the path to your downloaded datasets to make sure there is no hidden bugs.

可以发我邮箱（michaelxuus at hotmail dot com）讨论，这里一条一条回好像不是很有效率

**Comment by futureisatyourhand** [comment]
> > Hello, what is the configuration of your server environment? As configured by the author, I train 150 epochs, but the detection result is much worse than yours for base classes.
> > Thank your reply!
> 
> I followed the author's config and environment pretty much exactly. So I am not very sure why training on different servers results quite different results. Perhaps run through the path to your downloaded datasets to make sure there is no hidden bugs.
> 
> 可以发我邮箱（michaelxuus at hotmail dot com）讨论，这里一条一条回好像不是很有效率

My weichat is futureisatyourhand. Can you add my WeChat? Thanks!

**Comment by infrontofme** [comment]
Hi, Have new classes been used to train the base model?
