### ISSUE TITLE
 In the few-shot fine-tuning phase, As only k labeled bounding boxes are available for the novel classes, we also include k boxes for each base class.

### ISSUE THREAD

**Issue by zhoushuang66** [bingykang/Fewshot_Detection#44]
paper:The second phase is few-shot fine-tuning. In this phase, we train the model on both base and novel classes. As only k labeled bounding boxes are available for the novel classes, to balance between samples from the base and novel classes, we also include k boxes for each base class. (3.2. Learning Scheme  Section ).
but the code that Feature Extractor learner label is large data (from train = /home/bykang/voc/voc_train.txt) In the few-shot fine-tuning phase.  Do you have any suggestion or solution? can you help me? thanks.

**Comment by zhoushuang66** [comment]
I know this problem, thanks.

**Comment by chouxianyu** [comment]
I have the same question ! Would you like to help me? 
Thanks.
@zhoushuang66
