### ISSUE TITLE
No such file or directory: 'path/toweightfile'  when evaluating the model

### ISSUE THREAD

**Issue by cgg99** [bingykang/Fewshot_Detection#56]
After training the model, I execute `python valid_ensemble.py cfg/metayolo_novel0.data cfg/darknet_dynamic.cfg cfg/reweighting_net.cfg path/toweightfile` but the file"path/toweightfile" doesn't exist. There are only “backup/metayolo_novel0_neg1/xxxxxx.weights”file generated after training the model.

Could someone help me solve the problem？Thanks a lot!!

**Comment by cgg99** [comment]
@bingykang Sorry to trouble you. Could you help me solve the problem？Thanks a lot!!

**Comment by lander1003** [comment]
Have you solven the problem now?
