### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'backup/metayolo_novel0_neg1'

### ISSUE THREAD

**Issue by DL-Alva** [bingykang/Fewshot_Detection#6]
When I run 
python train_meta.py cfg/metayolo.data cfg/darknet_dynamic.cfg cfg/reweighting_net.cfg darknet19_448.conv.23

A FileNotFoundError occured:
FileNotFoundError: [Errno 2] No such file or directory: 'backup/metayolo_novel0_neg1'

Do you know what's wrong? Thank you so much.

**Comment by christegho** [comment]
I think the solution to this error is to create the folder backup
